# docker-compose.yml
version: '3'
services:
  ride-sharing-backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - API_KEY=${API_KEY}
    volumes:
      - ./src:/app/src
    restart: unless-stopped